# Generated by Django 5.1.5 on 2025-02-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
