version: '3.8'

services:
  backend:
    build: .
    command: python intelliwear/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=require
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  frontend:
    image: muhammadsaadnawaz49/intelliwear-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:6
    ports:
      - "6379:6379"